In [21]:
import requests
import json
import base64
import tensorflow as tf
import io
from PIL import Image

In [22]:
image_data=tf.io.read_file('object-detection-SMALL_2_files\\000000150805.jpg')
image_data

<tf.Tensor: shape=(), dtype=string, numpy=b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01\x00H\x00H\x00\x00\xff\xed\x1a\xacPhotoshop 3.0\x008BIM\x04\x04\x00\x00\x00\x00\x01\xe9\x1c\x01Z\x00\x03\x1b%G\x1c\x02\x00\x00\x02O\t\x1c\x02x\x00.\r\rhttp://www.flickr.com/photos/tk_five_0/show/\x1c\x02z\x00\rMichael Dawes\x1c\x02i\x00"Lots of wind and RAIN.............\x1c\x02(\x00\rMichael Dawes\x1c\x02P\x00\x1aPhotographer:Michael Dawes\x1c\x02U\x00\x17Professional Lay-a-bout\x1c\x02n\x00\rMichael Dawes\x1c\x02s\x00\x19Michael Dawes Photography\x1c\x027\x00\x0820101010\x1c\x02<\x00\x0b094106+0000\x1c\x02Z\x00\nGold Coast\x1c\x02\\\x00\x06Robina\x1c\x02_\x00\nQueensland\x1c\x02e\x00\tAustralia\x1c\x02d\x00\x03+61\x1c\x02g\x00\x07At Play\x1c\x02\x19\x00\tAustralia\x1c\x02\x19\x00\x0eBurleigh Heads\x1c\x02\x19\x00\x15Burleigh Heads Locals\x1c\x02\x19\x00\x07Country\x1c\x02\x19\x00\nGold Coast\x1c\x02\x19\x00\nQueensland\x1c\x02\x19\x00\x07Surfing\x1c\x02\x19\x00\x05Towns\x1c\x02t\x00\tCopyright\x00

In [23]:
# Encode the tensor as base64
encoded_tensor = tf.io.encode_base64(image_data)

# Decode the byte string to UTF-8 string
base64_string = encoded_tensor.numpy().decode('utf-8')

print(base64_string)

_9j_4AAQSkZJRgABAQEASABIAAD_7RqsUGhvdG9zaG9wIDMuMAA4QklNBAQAAAAAAekcAVoAAxslRxwCAAACTwkcAngALg0NaHR0cDovL3d3dy5mbGlja3IuY29tL3Bob3Rvcy90a19maXZlXzAvc2hvdy8cAnoADU1pY2hhZWwgRGF3ZXMcAmkAIkxvdHMgb2Ygd2luZCBhbmQgUkFJTi4uLi4uLi4uLi4uLi4cAigADU1pY2hhZWwgRGF3ZXMcAlAAGlBob3RvZ3JhcGhlcjpNaWNoYWVsIERhd2VzHAJVABdQcm9mZXNzaW9uYWwgTGF5LWEtYm91dBwCbgANTWljaGFlbCBEYXdlcxwCcwAZTWljaGFlbCBEYXdlcyBQaG90b2dyYXBoeRwCNwAIMjAxMDEwMTAcAjwACzA5NDEwNiswMDAwHAJaAApHb2xkIENvYXN0HAJcAAZSb2JpbmEcAl8AClF1ZWVuc2xhbmQcAmUACUF1c3RyYWxpYRwCZAADKzYxHAJnAAdBdCBQbGF5HAIZAAlBdXN0cmFsaWEcAhkADkJ1cmxlaWdoIEhlYWRzHAIZABVCdXJsZWlnaCBIZWFkcyBMb2NhbHMcAhkAB0NvdW50cnkcAhkACkdvbGQgQ29hc3QcAhkAClF1ZWVuc2xhbmQcAhkAB1N1cmZpbmccAhkABVRvd25zHAJ0AAlDb3B5cmlnaHQAOEJJTQQlAAAAAAAQwHWyam4Xbns6enEgjV6RLThCSU0EOgAAAAAAkwAAABAAAAABAAAAAAALcHJpbnRPdXRwdXQAAAAFAAAAAENsclNlbnVtAAAAAENsclMAAAAAUkdCQwAAAABJbnRlZW51bQAAAABJbnRlAAAAAENscm0AAAAATXBCbGJvb2wBAAAAD3ByaW50U2l4dGVlbkJpdGJvb2wAAAAAC3ByaW50ZXJOYW1lVEVYVAAAAAEAAAA4QklNBDsAAAAAAbIAAAAQAAAAAQAA

In [24]:
# Convert the base64 string to a byte string
byte_string = base64_string.encode('utf-8')

# Decode the byte string to a TensorFlow tensor
decoded_tensor = tf.io.decode_base64(byte_string)
decoded_tensor

<tf.Tensor: shape=(), dtype=string, numpy=b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01\x00H\x00H\x00\x00\xff\xed\x1a\xacPhotoshop 3.0\x008BIM\x04\x04\x00\x00\x00\x00\x01\xe9\x1c\x01Z\x00\x03\x1b%G\x1c\x02\x00\x00\x02O\t\x1c\x02x\x00.\r\rhttp://www.flickr.com/photos/tk_five_0/show/\x1c\x02z\x00\rMichael Dawes\x1c\x02i\x00"Lots of wind and RAIN.............\x1c\x02(\x00\rMichael Dawes\x1c\x02P\x00\x1aPhotographer:Michael Dawes\x1c\x02U\x00\x17Professional Lay-a-bout\x1c\x02n\x00\rMichael Dawes\x1c\x02s\x00\x19Michael Dawes Photography\x1c\x027\x00\x0820101010\x1c\x02<\x00\x0b094106+0000\x1c\x02Z\x00\nGold Coast\x1c\x02\\\x00\x06Robina\x1c\x02_\x00\nQueensland\x1c\x02e\x00\tAustralia\x1c\x02d\x00\x03+61\x1c\x02g\x00\x07At Play\x1c\x02\x19\x00\tAustralia\x1c\x02\x19\x00\x0eBurleigh Heads\x1c\x02\x19\x00\x15Burleigh Heads Locals\x1c\x02\x19\x00\x07Country\x1c\x02\x19\x00\nGold Coast\x1c\x02\x19\x00\nQueensland\x1c\x02\x19\x00\x07Surfing\x1c\x02\x19\x00\x05Towns\x1c\x02t\x00\tCopyright\x00

In [25]:
image_data==decoded_tensor

<tf.Tensor: shape=(), dtype=bool, numpy=True>